/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "IDAO",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDAO__factory>;
    getContractFactory(
      name: "IIDAO",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IIDAO__factory>;
    getContractFactory(
      name: "IUniswapV2Router01",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IUniswapV2Router01__factory>;
    getContractFactory(
      name: "IUniswapV2Router02",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IUniswapV2Router02__factory>;
    getContractFactory(
      name: "InvestorDao",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.InvestorDao__factory>;
    getContractFactory(
      name: "FakeUniswapPair",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FakeUniswapPair__factory>;
    getContractFactory(
      name: "FakeUniswapRouter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FakeUniswapRouter__factory>;
    getContractFactory(
      name: "TestToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TestToken__factory>;
    getContractFactory(
      name: "UniswapUtilities",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UniswapUtilities__factory>;

    getContractAt(
      name: "ERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "IDAO",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IDAO>;
    getContractAt(
      name: "IIDAO",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IIDAO>;
    getContractAt(
      name: "IUniswapV2Router01",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IUniswapV2Router01>;
    getContractAt(
      name: "IUniswapV2Router02",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IUniswapV2Router02>;
    getContractAt(
      name: "InvestorDao",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.InvestorDao>;
    getContractAt(
      name: "FakeUniswapPair",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.FakeUniswapPair>;
    getContractAt(
      name: "FakeUniswapRouter",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.FakeUniswapRouter>;
    getContractAt(
      name: "TestToken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.TestToken>;
    getContractAt(
      name: "UniswapUtilities",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.UniswapUtilities>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
